In [6]:
import numpy as np
import open3d

pcd = open3d.io.read_point_cloud("bun000.ply")
print(pcd)    # 打印点的总数
print(np.asarray(pcd.points))    # 打印实际点云的坐标数据

open3d.visualization.draw_geometries([pcd])

PointCloud with 40256 points.
[[-0.06325    0.0359793  0.0420873]
 [-0.06275    0.0360343  0.0425949]
 [-0.0645     0.0365101  0.0404362]
 ...
 [-0.01575    0.187201  -0.0220209]
 [-0.01525    0.187218  -0.0237782]
 [-0.018      0.18794   -0.0197253]]


In [9]:
down_pcd = pcd.voxel_down_sample(voxel_size = 0.01)   # 下采样
open3d.visualization.draw_geometries([down_pcd])
